name: Operation Check

on:
    schedule:
      # * is a special character in YAML so you have to quote this string
      - cron:  '30 5,17 * * *'

jobs:
    Confirmation of EasyPipeline operation:
      runs-on: ubuntu-22.04
       steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: master
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools twine build
          pip install -U torch --index-url https://download.pytorch.org/whl/cpu
          pip install -U diffusers

      - name: Build release distributions
        run: |
          python -m build

      - name: Publish release distributions to test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          attestations: false
          repository-url: https://test.pypi.org/legacy/

      - name: Test installing auto_diffusers and importing
        run: |
          pip install auto_diffusers && pip uninstall auto_diffusers -y
          pip install -i https://test.pypi.org/simple/ auto-diffusers
          python -c "from auto_diffusers import __version__; print(__version__)"
          python -c "from auto_diffusers import EasyPipelineForText2Image; pipe = EasyPipelineForText2Image.from_huggingface('Stable Diffusion')"
          python -c "from auto_diffusers import EasyPipelineForText2Image; pipe = EasyPipelineForText2Image.from_civitai('DreamShaper')"
          python -c "from auto_diffusers import *"